apiVersion: v1
kind: Deployment
metadata:
  namespace: dev
  labels:
    app: myapp
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  strategy: {}
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: sneha123.azurecr.io
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: lb-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp
  type: LoadBalancer
---
